version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: chandan
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: employee_dbs
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-s-data:/var/lib/mysql


networks:
  my-network:
    driver: bridge

volumes:
  mysql-s-data: